### ISSUE TITLE
How to create a date without year?

### ISSUE THREAD

**Issue by xjlin0** [ktowen/django-partial-date-field#5]
Hi, it's great library! One question, if only month and day are available, could django_partial_date store only month and day without year? something like:
```
dob=PartialDate(datetime.date(0, 9, 21), precision=PartialDate.DAY)
```
Thanks!

**Comment by ktowen** [comment]
Hi @xjlin0, thanks for your comment. Currently this is not possible and I don't think it would be as it's outside the scope of this extension. Greetings
